apps/job/urls.py
from django.urls import path

from .api import api_search
from .views import apply_for_job, job_detail, add_job, edit_job, search

urlpatterns = [
    path('api/search/', api_search, name='api_search'),
    path('search/', search, name='search'),
    path('add/', add_job, name='add_job'),
    path('<int:job_id>/', job_detail, name='job_detail'),
    path('<int:job_id>/edit', edit_job, name='edit_job'),
    path('<int:job_id>/apply', apply_for_job, name='apply_for_job'),
]

codingjobs/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, include
from django.conf.urls.static import static
from django.contrib.auth import views

from apps.core.views import index

urlpatterns = [
    path('', index, name='index'),
    path('', include('apps.authentication.urls')),
    path('api/', include('apps.api.urls')),
    path('admin/', admin.site.urls),
    path('dashboard/', include('apps.userprofile.urls')),
    path('jobs/', include('apps.job.urls')),
    path('notifications/', include('apps.notification.urls')),
    path('summernote/', include('django_summernote.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

apps/job/models.py
from curses.ascii import SI
from email.policy import default
from django.contrib.auth.models import User
from django.db import models


class Job(models.Model):
    SIZE_1_9 = 'size_1-9'
    SIZE_10_49 = 'size_10-49'
    SIZE_50_99 = 'size_50-99'
    SIZE_100 = 'size_100'

    CHOICES_SIZE = (
        (SIZE_1_9, '1-9'),
        (SIZE_10_49, '10-49'),
        (SIZE_50_99, '50-99'),
        (SIZE_100, '100'),
    )

    ACTIVE = 'active'
    EMPLOYED = 'employed'
    ARCHIVED = 'archived'

    CHOICES_STATUS ={
        (ACTIVE, 'Active'),
        (EMPLOYED, 'Employed'),
        (ARCHIVED, 'Archived'),
    }

    title = models.CharField(max_length=255)
    short_description = models.TextField()
    long_description = models.TextField(blank=True, null=True)
    company_name = models.CharField(max_length=255)
    company_address = models.CharField(max_length=255, blank=True, null=True)
    company_zipcode = models.CharField(max_length=255, blank=True, null=True)
    company_place = models.CharField(max_length=255, blank=True, null=True)
    company_country = models.CharField(max_length=255, blank=True, null=True)
    company_size = models.CharField(
        max_length=20, choices=CHOICES_SIZE, default=SIZE_1_9)

    created_by = models.ForeignKey(
        User, related_name='jobs', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    changed_at = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=20, choices=CHOICES_STATUS, default=ACTIVE)

    def __str__(self) -> str:
        return self.title


class Application(models.Model):
    job = models.ForeignKey(
        Job, related_name='applications', on_delete=models.CASCADE)
    content = models.TextField()
    experience = models.TextField()

    created_by = models.ForeignKey(
        User, related_name='applications', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self) -> str:
        return "Job: %s - Cadidate: %s" % (self.job, self.created_by)

apps/models/Job.py
from django.contrib.auth.models import User
from django.db import models
from .enums import StatusEnum, BooleanEnums, CategoryEnum, JobTypeEnum


class Job(models.Model):

    status = models.CharField(
        max_length=20, choices=StatusEnum.choices(), default=StatusEnum.get_value('ACTIVE'))
    title = models.CharField(max_length=255)
    description = models.TextField()
    category = models.CharField(
        max_length=50, choices=CategoryEnum.choices())
    skills = models.TextField(blank=True, null=True)
    is_worldwide = models.CharField(
        max_length=1, choices=BooleanEnums.choices(), default=BooleanEnums.get_value('YES'))
    job_type = models.CharField(max_length=20, choices=JobTypeEnum.choices())
    application_link = models.CharField(max_length=255, blank=True, null=True)
    company_name = models.CharField(max_length=255)
    company_hq = models.CharField(max_length=255)
    company_website = models.CharField(max_length=255)
    company_logo = models.FileField(upload_to='logos/')
    company_email = models.EmailField(max_length=255)
    company_description = models.TextField(blank=True, null=True)

    created_by = models.ForeignKey(
        User, related_name='jobs', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    changed_at = models.DateTimeField(auto_now=True)

    def __str__(self) -> str:
        return "{} | {}".format(self.title, self.company_name)

apps/job/forms.py
from django import forms
from django_summernote.widgets import SummernoteWidget
from apps.models.Job import Job
from apps.models.Application import Application


class AddJobForm(forms.ModelForm):
    class Meta:
        model = Job
        widgets = {
            'title': forms.TextInput(
                attrs={
                    'class': 'input',
                    'v-model': 'form.title'
                }
            ),
            'description': SummernoteWidget(attrs={
                'v-model': 'form.description'
            }),
            'category': forms.Select(attrs={
                'v-model': 'form.category'
            }),
            'application_link': forms.TextInput(
                attrs={
                    'class': 'input',
                    'v-model': 'form.application_link'
                }
            ),
            'company_name': forms.TextInput(
                attrs={
                    'class': 'input',
                    'v-model': 'form.company_name'
                }
            ),
            'company_hq': forms.TextInput(
                attrs={
                    'class': 'input',
                    'v-model': 'form.company_hq'
                }
            ),
            'company_logo': forms.FileInput(attrs={
                'class': 'is-hidden',
                'style': 'cursor: pointer'
            }),
            'company_website': forms.TextInput(
                attrs={
                    'class': 'input',
                    'v-model': 'form.company_website'
                }
            ),
            'company_email': forms.TextInput(
                attrs={
                    'class': 'input',
                    'v-model': 'form.company_email'
                }
            ),
            'company_description': SummernoteWidget(attrs={
                'v-model': 'form.company_description'
            }),
        }
        fields = ('title', 'description', 'category', 'skills', 'is_worldwide',
                  'job_type', 'application_link', 'company_name', 'company_hq', 'company_website', 'company_logo', 'company_email', 'company_description')


class ApplicationForm(forms.ModelForm):
    class Meta:
        model = Application
        fields = ['content', 'experience']

apps/job/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404, redirect, render

from apps.job.forms import AddJobForm, ApplicationForm
from apps.notification.utilities import create_notification
from apps.models.Job import Job


def search(request):
    return render(request, 'job/search.html')


def job_detail(request, job_id):
    job = Job.objects.get(pk=job_id)

    return render(request, 'job/job_detail.html', {'job': job})


@login_required
def add_job(request):
    if request.method == 'POST':
        form = AddJobForm(request.POST)

        if form.is_valid():
            job = form.save(commit=False)
            job.created_by = request.user
            job.save()

            return redirect('dashboard')
    else:
        form = AddJobForm()
    return render(request, 'job/add_job.html', {'form': form})


@login_required
def edit_job(request, job_id):
    job = get_object_or_404(Job, pk=job_id, created_by=request.user)

    if request.method == 'POST':
        form = AddJobForm(request.POST, instance=job)

        if form.is_valid():
            job = form.save(commit=False)
            job.status = request.POST.get('status')
            job.save()

            return redirect('dashboard')
    else:
        form = AddJobForm(instance=job)
    return render(request, 'job/edit_job.html', {'form': form, 'job': job})


@login_required
def apply_for_job(request, job_id):
    job = Job.objects.get(pk=job_id)

    if request.method == 'POST':
        form = ApplicationForm(request.POST)

        if form.is_valid():
            application = form.save(commit=False)
            application.job = job
            application.created_by = request.user
            application.save()

            create_notification(request, job.created_by,
                                'application', extra_id=application.id)

            return redirect('dashboard')
    else:
        form = ApplicationForm()
    return render(request, 'job/apply_for_job.html', {'form': form, 'job': job})

apps/job/templates/job/apply_for_job.html
{% extends 'layouts/base.html' %} 

{% block content %}
  <h1 class="title">Apply for job - {{ job.title }}</h1>
  <form method="post">
    {% csrf_token %}

    {% if form.errors %}
      {% for error in form.errors %}
        <div class="notification is-danger">
          {{ error }}
        </div>
      {% endfor %}
    {% endif %}

    <div class="field">
      <label>Content</label>
      <div class="control">
        <textarea class="textarea" name="content" id="id_content"></textarea>
      </div>
    </div>

    <div class="field">
      <label>Experience</label>
      <div class="control">
        <textarea class="textarea" name="experience" id="id_experience"></textarea>
      </div>
    </div>

    <div class="field">
      <div class="control">
        <button class="button is-success">Submit</button>
      </div>
    </div>
  </form>
{% endblock %}

apps/job/templates/job/edit_job.html
{% extends 'layouts/base.html' %} 

{% block content %}
  <div id="edit-job-app">
    <h1 class="title">Add job</h1>
    <form method="post" v-on:submit="validateForm">
      {% csrf_token %}

      <div class="notification is-danger" v-if="errors.length">
        <p v-for="error in errors">
          [[ error ]]
        </p>
      </div>

      <div class="field">
        <label>Title</label>
        <div class="control">
          <input type="text" class="input" name="title" id="id_title" v-model="form.title">
        </div>
      </div>

      <div class="field">
        <label>Short description</label>
        <div class="control">
          <textarea class="textarea" name="short_description" id="id_short_description" v-model="form.short_description"></textarea>
        </div>
      </div>

      <div class="field">
        <label>Long description</label>
        <div class="control">
          <textarea class="textarea" name="long_description" id="id_long_description">{% if job.long_description %}{{ job.long_description }}{% endif %}</textarea>
        </div>
      </div>

      <div class="field">
        <label>Company name</label>
        <div class="control">
          <input type="text" class="input" name="company_name" id="id_company_name" v-model="form.company_name">
        </div>
      </div>

      <div class="field">
        <label>Company address</label>
        <div class="control">
          <input type="text" class="input" name="company_address" id="id_company_address" value="{% if job.company_address %}{{ job.company_address }}{% endif %}">
        </div>
      </div>

      <div class="field">
        <label>Company zipcode</label>
        <div class="control">
          <input type="text" class="input" name="company_zipcode" id="id_company_zipcode" vale="{% if job.company_zipcode %}{{ job.company_zipcode }}{% endif %}">
        </div>
      </div>

      <div class="field">
        <label>Company place</label>
        <div class="control">
          <input type="text" class="input" name="company_place" id="id_company_place" value="{% if job.company_place %}{{ job.company_place }}{% endif %}">
        </div>
      </div>

      <div class="field">
        <label>Company country</label>
        <div class="control">
          <input type="text" class="input" name="company_contry" id="id_company_country" value="{% if job.company_country %}{{ job.company_country }}{% endif %}">
        </div>
      </div>

      <div class="field">
        <label for="company_size">Company size</label>
        <div class="control">
          <div class="select">
            <select name="company_size" id="id_company_size" v-model="form.company_size">
              <option value="" selected>Choose size</option>
              <option value="size_1-9">1-9</option>
              <option value="size_10-49">10-49</option>
              <option value="size_50-99">50-99</option>
              <option value="size_100">100+</option>
            </select>
          </div>
        </div>
      </div>

      <div class="field">
        <label for="status">Status</label>
        <div class="control">
          <div class="select">
            <select name="status" id="id_status" >
              <option value="active" {% if job.status == 'active' %} selected {% endif %}>Active</option>
              <option value="employed" {% if job.status == 'employed' %} selected {% endif %}>Employed</option>
              <option value="archived" {% if job.status == 'archived' %} selected {% endif %}>Archived</option>
            </select>
          </div>
        </div>
      </div>

      <div class="field">
        <div class="control">
          <button class="button is-success">Submit</button>
        </div>
      </div>
    </form>
  </div>
{% endblock %}

{% block scripts %}
<script>
  const AddJobApp = {
    data() {
      return {
        form: {
          title: '{{ job.title }}',
          company_name: '{{ job.company_name }}',
          short_description: '{{ job.short_description }}',
          company_size: '{{ job.company_size }}',
        },
        errors: [],
      }
    },
    delimiters: ['[[', ']]'],
    methods: {
      validateForm(e) {
        this.errors = [];

        Object.entries(this.form).forEach(([key, value]) => {
          if(!value) {
            this.errors.push(`The ${key.replace('_', ' ')} field is missing!`);
          }
        })

        if (this.errors.length) {
          e.preventDefault();
          return false;
        }
        return true;
      }
    }
  }

  Vue.createApp(AddJobApp).mount('#edit-job-app');
</script>
{% endblock %}

apps/job/templates/job/job_detail.html
{% extends 'layouts/base.html' %} {% block content %}
  <h1 class="title">{{ job.title }} ({{ job.get_status_display }})</h1>
  <p class="is-size-4">{{ job.short_description }}</p>
  <p>{{ job.long_description }}</p>

  <b>Company name: </b>{{ job.company_name }}<br>
  {% if job.company_address %}<b>Company address: </b>{{ job.company_address }}<br>{% endif %}
  {% if job.company_zipcode %}<b>Company zipcode: </b>{{ job.company_zipcode }}<br>{% endif %}
  {% if job.company_place %}<b>Company place: </b>{{ job.company_place }}<br>{% endif %}
  {% if job.company_country %}<b>Company country: </b>{{ job.company_country }}<br>{% endif %}
  <b>Company size: </b>{{ job.get_company_size_display }}<br>
  {% if job.status == 'active' %}
    <a href="{% url 'apply_for_job' job.id %}" class="button is-success">Apply for job</a>
  {% else %}
    <p>This job is not available anymore!</p>
  {% endif %}
{% endblock %}

apps/job/templates/job/search.html
{% extends 'layouts/base.html' %}

{% block content %}
  <div id="search-app">
    <h1 class="title">Search</h1>
    
    <form v-on:submit.prevent="performSearch()">
      <div class="columns">
        <div class="column is-4">
          <div class="field">
            <label for="query">Query</label>
            <div class="control">
              <input type="text" name="query" class="input" v-model="query">
            </div>
          </div>

          <div class="field">
            <label for="company_size">Company size</label>
            <div class="control">
              <div class="select">
                <select name="company_size" id="id_company_size" v-model="company_size">
                  <option value="" selected>All</option>
                  <option value="size_1-9">1-9</option>
                  <option value="size_10-49">10-49</option>
                  <option value="size_50-99">50-99</option>
                  <option value="size_100">100+</option>
                </select>
              </div>
            </div>
          </div>

          <div class="field">
            <div class="control">
              <button class="button is-success">Search</button>
            </div>
          </div>
        </div>
      </div>
    </form>

    <div v-if="jobs.length">
      <hr>
      <div v-for="job in jobs" :key="job.id" class="notification mt-2">
        <h3 class="is-size-4">[[ job.title ]]</h3>
        <p>[[ job.company_name ]]</p>
        <a :href="job.url">View details</a>
      </div>
    </div>
  </div>
{% endblock %}

{% block javascripts %}
<script>
  const SearchApp = {
    data() {
      return {
        query: '',
        company_size: '',
        jobs: [],
      }
    },
    delimiters: ['[[', ']]'],
    methods: {
      performSearch() {
        const data = {
          'query': this.query,
          'company_size': this.company_size,
        }

        fetch('/jobs/api/search/', {
          method: 'POST',
          headers: {
            'Content-Type': 'application/json',
            'X-CSRFToken': '{{ csrf_token }}',
          },
          body: JSON.stringify(data)
        })
          .then((response) => {
            return response.json();
          })
          .then((result) => {
            this.jobs = result.jobs;
          })
          .catch((error) => {
            console.log(error)
          });
      }
    }
  }

  Vue.createApp(SearchApp).mount('#search-app');
</script>
{% endblock %}